name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: DEBIAN_FRONTEND="noninteractive" apt-get update && apt-get -y install tzdata
      - run: apt-get update \
  && apt-get install -y software-properties-common wget \
  && add-apt-repository ppa:ubuntu-toolchain-r/test \
  && apt-get install -y gcc-10 g++-10 make libssl-dev \
  && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 1000 --slave /usr/bin/g++ g++ /usr/bin/g++-10 \
  && update-alternatives --auto gcc \
  && apt-get clean
      - run: wget https://cmake.org/files/v3.18/cmake-3.18.0.tar.gz \
  && tar xvzf cmake-3.18.0.tar.gz \
  && cd cmake-3.18.0/ \
  && ./bootstrap \
  && make -j8 \
  && make install
      - run: apt install g++
      - run: g++ main.cpp
      - run: ./a.out
